INSERT INTO APP.BUSSINESENTITYTYPE (DESCRIPTION, LABEL, "NAME") 
	VALUES ("Entidad de negocio", 'BussinesEntity', 'BussinesEntity');
INSERT INTO APP.BUSSINESENTITY (ENTITY_TYPE, ACTIVATIONTIME, ACTIVE, CODE, CODETYPE, CREATEDON, DESCRIPTION, EXPIRATIONTIME, LASTUPDATE, "NAME", PRIORITY, STATUS, VERSION, DELETED, DELETEDON, AUTHOR, ORGANIZATION_ID, PROPERTY_ID, TYPE_ID) 
	VALUES ('1', '2015-02-02 23:28:45.799', true, '1', x'31', CURRENT_TIMESTAMP, '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '11111', 1, 'OK', 1, true, CURRENT_TIMESTAMP, NULL, NULL, NULL, 1)

